default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  # port: 5432
  # host: host.docker.internal
 
development:
  <<: *default
  database: api_development

